// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsIx_tXKELeH7brUYQJiNTphVQE4Dpaoc',
    appId: '1:530313661506:web:3d73d77d020b48965a71db',
    messagingSenderId: '530313661506',
    projectId: 'a-i-t-374e0',
    authDomain: 'a-i-t-374e0.firebaseapp.com',
    databaseURL: 'https://a-i-t-374e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'a-i-t-374e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXdcrdZnbh4DjJsuRx3CDJT_mQqrCu2c8',
    appId: '1:530313661506:android:96153a22e4d6b7dc5a71db',
    messagingSenderId: '530313661506',
    projectId: 'a-i-t-374e0',
    databaseURL: 'https://a-i-t-374e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'a-i-t-374e0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsIx_tXKELeH7brUYQJiNTphVQE4Dpaoc',
    appId: '1:530313661506:web:e3664930dde078d95a71db',
    messagingSenderId: '530313661506',
    projectId: 'a-i-t-374e0',
    authDomain: 'a-i-t-374e0.firebaseapp.com',
    databaseURL: 'https://a-i-t-374e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'a-i-t-374e0.firebasestorage.app',
  );
}
